### ISSUE TITLE
About the extractor.py

### ISSUE THREAD

**Issue by 11510880** [anuragkr90/weak_feature_extractor#1]
Hello, when I run the feat_extractor.py, the console shows that   for k, mod in model._modules.iteritems():

AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems' 
It seems that something went wrong with extractor.py.

**Comment by anuragkr90** [comment]
Are you using python 3.x ? If so then changing 'iteritems' to 'items' should work.

**Comment by 11510880** [comment]
OK,it works.Thank you very much!
