### ISSUE TITLE
use of netwrkgpl

### ISSUE THREAD

**Issue by krantiparida** [anuragkr90/weak_feature_extractor#3]
In line 22 of feat_extractor.py, it is mentioned that netwrkgpl should be fixed.
"netwrkgpl = Fx.avg_pool2d # keep it fixed"

Going through the code flow it seems that netwrkgpl is never used. Is there any significance of keeping fixed this variable?

**Comment by anuragkr90** [comment]
That was used in training. The network was trained with avg pooling. If you are extracting features then you dont need it.
